spring.application.name=ecologistics
spring.datasource.url=jdbc:postgresql://localhost:5432/ecologistics_db
spring.datasource.username=postgres
spring.datasource.password=93366162
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
